### ISSUE TITLE
Use of undeclared identifier 'DBL_EPSILON'

### ISSUE THREAD

**Issue by ericrisler** [boredzo/iso-8601-date-formatter#34]
Hi, 

Trying to compile this into a static library and run in both the simulator and Instruments (Xcode 5.0.2, iOS SDK 7) I get an undefined error. At the top of the .m file you conditionally include the UIKit.h (which, if included removes this problem) if TARGET_OS_IPHONE is defined.

To get this to compile for the simulator, I had to add "|| TARGET_IPHONE_SIMULATOR" to the condition. 

Any idea how to get it to compile for instruments?

**Comment by boredzo** [comment]
This seems to be working as of 0.8 and Xcode 7.3.
