### ISSUE TITLE
Time zone has the sign in the middle

### ISSUE THREAD

**Issue by boredzo** [boredzo/iso-8601-date-formatter#36]
Reported by Zac West via Twitter: https://twitter.com/zacwest/status/423243320626651136

STR welcome.

**Comment by bejar37** [comment]
Any chance that this fix will ever be released to cocoapods?

**Comment by boredzo** [comment]
That's up to @iOSCowboy. If you want to submit a pull request, I'd be willing to merge it in.

**Comment by iOSCowboy** [comment]
I think it has already been merged. There is no difference when i compare the branches for PR.

**Comment by boredzo** [comment]
Oh, you're right! I merged this in [90f6cf0]. Sorry for the noise.

So, yeah, this will be in all future releases.

**Comment by justinseanmartin** [comment]
Any chance you'd consider publishing a podspec with this fix?
