### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [boredzo/iso-8601-date-formatter#49]
When I searched the CocoaPods site for this library, one [result](http://cocoapods.org/?q=iso-8601-date-formatter) shows up.

Then I went and added it to my `Podfile`, ran `pod install` but I got the following error.
**Unable to find a specification for `iso-8601-date-formatter`**

Can you please implement CocoaPods support for your library? I'd really appreciate it.

Thanks.

**Comment by boredzo** [comment]
It's already implemented. [I filed a bug about their search page.](https://github.com/CocoaPods/Specs/issues/12926)

Try `pod install ISO8601DateFormatter`.

**Comment by Isuru-Nanayakkara** [comment]
Got it! Thank you. `pod 'ISO8601DateFormatter'` works.
