### ISSUE TITLE
Update Podspec to support watchOS 2

### ISSUE THREAD

**Issue by leviathan** [boredzo/iso-8601-date-formatter#54]
When using `ISO8601DateFormatter` with `watchOS 2`, then I get this error message when running `pod install`

```
[!] The platform of the target `XXXX` (watchOS 2.0) is not compatible with `ISO8601DateFormatter (0.7)`, which does not support `watchos`.
```

Please update the podspec for `ISO8601DateFormatter` to support watchOS 2.

Here's the Cocoapods blog entry: http://blog.cocoapods.org/CocoaPods-0.38/

**Comment by boredzo** [comment]
This is done in the 0.8 podspec, as that version supports all four platforms.
