### ISSUE TITLE
Carthage build fails under 10.11

### ISSUE THREAD

**Issue by vasarhelyia** [boredzo/iso-8601-date-formatter#57]
I received [this issue](https://github.com/brewfactory/BrewMobile/issues/50) the other day on my project and it seems this problem occurs under OS X 10.11 & Xcode 7.1 with the framework. 

Building the project with Carthage gives an error like it's unable to find destination and the destination was a Core Simulator iPhone 4S, iOS 9.1. I've checked the build settings of the `ISO8601` framework target and the only thing unfamiliar to me is that the architectures were not set to Standard (armv7, arm64). I gave it a try [setting it standard](https://github.com/vasarhelyia/iso-8601-date-formatter/commit/7f7aa6a39cd140ee48c0a628c4169d51144fb72e) and it solved this issue. 

I've created an issue, not a PR because I'm not aware of why do you have different settings for architecture, I would appreciate your help clarifying it. Honestly, I have no idea why does setting it to standard solve this problem if it worked perfectly under 10.10 and Xcode 7.0, couldn't find any useful information about it. It might even be a Carthage issue, I will ask them for help as well.

**Comment by boredzo** [comment]
I think this might be left over from ISO 8601 Date Formatter's days as a Mac-only, iOS-not-terribly-prioritized thing. Setting the architectures to ARCHS_STANDARD_64_BIT specifically excludes 32-bit—in the context of the Mac, meaning i386, which has the Legacy Runtime.

On Apple's other platforms, that doesn't make sense.

I'm going to push a branch with ARCHS set to standard in the project and overridden at the same level for Mac SDKs. Stand by.

**Comment by boredzo** [comment]
Please try that branch and let me know whether it fixes the issue.

**Comment by boredzo** [comment]
Green, FWIW: https://travis-ci.org/boredzo/iso-8601-date-formatter/builds/87398923

**Comment by vasarhelyia** [comment]
It builds with Carthage perfectly on the branch. Thanks a lot for the clarification and the modification!

**Comment by boredzo** [comment]
Thanks for the bug report!
