### ISSUE TITLE
Update version to include tvOS support

### ISSUE THREAD

**Issue by nielubowicz** [boredzo/iso-8601-date-formatter#60]
tvOS support was added in a recent commit: https://github.com/boredzo/iso-8601-date-formatter/commit/590e7cf76b504839de1cd8b3c2efab282ae78a27 and it would be very useful on my current project.

What is the time frame to get the new version of the pod published?

**Comment by pranavss11** [comment]
+1 @boredzo would be cool to have an updated pod.

**Comment by boredzo** [comment]
This was released this morning in 0.8.
