### ISSUE TITLE
-[ISO8601DateFormatter dateComponentsFromString:timeZone:range:fractionOfSecond:] (ISO8601DateFormatter.m:619)

### ISSUE THREAD

**Issue by rcastillop** [boredzo/iso-8601-date-formatter#61]
I've go this issue, with no extra details. 

There's a way to fix it, or avoid it?

1	libobjc.A.dylib	objc_msgSend + 2
2	CoreFoundation	-[__NSDictionaryM objectForKey:] + 128
3	MyApp	-[ISO8601DateFormatter dateComponentsFromString:timeZone:range:fractionOfSecond:] (ISO8601DateFormatter.m:619)
4	MyApp	-[ISO8601DateFormatter dateFromString:timeZone:range:] (ISO8601DateFormatter.m:692)
5	MyApp	-[ISO8601DateFormatter dateFromString:timeZone:] (ISO8601DateFormatter.m:686)

**Comment by rcastillop** [comment]
I think the issues is because there is not thread protection when we read or write to timeZonesByOffset.

**Comment by boredzo** [comment]
Ah, yes. I think this was fixed by #39—NSCache is thread-safe, whereas NSMutableDictionary is not.
