### ISSUE TITLE
Getting a false NSDate from string

### ISSUE THREAD

**Issue by robyzhou** [boredzo/iso-8601-date-formatter#63]
Hi,

I'm using this components to get a NSDate from a string obtained from Facebook API, but I found the NSDate is not right.

I tried the code bellow:

ISO8601DateFormatter* formatter = [[ISO8601DateFormatter alloc] init];
NSDate* date = [formatter dateFromString:@"2014-12-01"];
And I get the date as 2014-11-30 16:00:00 +0000, it's one day before 2014-12-01.

Yes, I'm in China, it looks right if we count the timezone element in.

But, I have tried other components on ISO8601, for example https://github.com/soffes/ISO8601
I tried the code the same as above, and I get the date as 1999-05-01 00:00:00 +0000

I have read the doc, didn't find any clue to get the same result as ISO8601 from this components.

Could you please teach me how to get a date as 2014-11-30 16:00:00 +0000 using this components?

Thanks in advance.

BR,
roby

**Comment by boredzo** [comment]
With this change, you'll be able to set `formatter.defaultTimeZone = [NSTimeZone timeZoneWithAbbreviation:@"UTC"]` to have `dateFromString:` resolve the components in UTC. Then that string returns the date you expected.

If I'm reading you right, @soffes's parser resolved that to 1995? You should file a bug report for that project, I think.

**Comment by robyzhou** [comment]
@boredzo Thank you for your help! And sorry for the typo, it's not 1995, it's 2014. Thanks again!
